Imports System.Data
Imports System.Data.OleDb
Imports MaterialDesignThemes.Wpf

Public Class AdminHome

    'Initialising database connection strings
    Dim con As New OleDbConnection
    Dim prov As String = "Provider = Microsoft.Jet.OLEDB.4.0;"
    Dim src As String = "Data Source=D:\VB Sources\Oceana Clinic Management\bin\Debug\Oceana.mdb"
    Dim ConnectionString As String = prov & src

    Public Sub New()

        'This call is required by the designer. <-- I didn't write this , it was autogenerated
        InitializeComponent()

        'Calling LoadGrid() class upon form load
        loadDataGrid()

    End Sub

    Public Sub loadDataGrid()

        'Loading Data from Access Database into DataGrid
        con.ConnectionString = ConnectionString

        Dim sql As String = "SELECT * FROM [User];"
        Dim ds As New DataSet
        Dim da As OleDb.OleDbDataAdapter

        da = New OleDb.OleDbDataAdapter(sql, con)
        da.Fill(ds, "User")
        dgUserList.ItemsSource = ds.Tables("User").DefaultView

    End Sub

    Private Sub btnEdit_Click(sender As Object, e As RoutedEventArgs) Handles btnEdit.Click

        If dgUserList.SelectedValue = Nothing Then

            'Selection validation 
            Dim msgqueue = New SnackbarMessageQueue(TimeSpan.FromSeconds(3))
            msgqueue.Enqueue("Please select a user")
            msgSnackbar.MessageQueue = msgqueue

        Else

            Using con As New OleDbConnection(ConnectionString)

                'SQL query to delete user record
                Dim sqlEdit As String = "UPDATE [User] SET [Password] = @Password, UserRole = @UserRole, Email = @Email, DisplayName = @DisplayName WHERE Username = @Username ;"

                'Supplying variable from selected datagrid
                Dim cmdDelete As New OleDbCommand(sqlEdit, con)
                cmdDelete.Parameters.AddWithValue("@Password", dgUserList.SelectedValue(1))
                cmdDelete.Parameters.AddWithValue("@UserRole", dgUserList.SelectedValue(2))
                cmdDelete.Parameters.AddWithValue("@Email", dgUserList.SelectedValue(3))
                cmdDelete.Parameters.AddWithValue("@DisplayName", dgUserList.SelectedValue(4))
                cmdDelete.Parameters.AddWithValue("@Username", dgUserList.SelectedValue(0))

                'Opening a connection and executing the query 
                con.Open()
                cmdDelete.ExecuteNonQuery()
                con.Close()

                'Refreshing datagrid
                loadDataGrid()

                'Update success message
                Dim msgqueue = New SnackbarMessageQueue(TimeSpan.FromSeconds(3))
                msgqueue.Enqueue("User info updated successfully")
                msgSnackbar.MessageQueue = msgqueue

            End Using

        End If

    End Sub

    Private Sub btnDelete_Click(sender As Object, e As RoutedEventArgs) Handles btnDelete.Click

        If dgUserList.SelectedValue = Nothing Then

            'Selection validation 
            Dim msgqueue = New SnackbarMessageQueue(TimeSpan.FromSeconds(3))
            msgqueue.Enqueue("Please select a user")
            msgSnackbar.MessageQueue = msgqueue

        Else

            Using con As New OleDbConnection(ConnectionString)

                'SQL query to delete user record
                Dim sqlDelete As String = "DELETE FROM [User] WHERE Username = @Username ;"

                'Supplying variable from selected datagrid
                Dim cmdDelete As New OleDbCommand(sqlDelete, con)
                cmdDelete.Parameters.AddWithValue("@Username", dgUserList.SelectedValue(0))

                'Opening a connection and executing the query 
                con.Open()
                cmdDelete.ExecuteNonQuery()
                con.Close()

                'Refreshing datagrid
                loadDataGrid()

                'Delete success message
                Dim msgqueue = New SnackbarMessageQueue(TimeSpan.FromSeconds(3))
                msgqueue.Enqueue("Record deleted")
                msgSnackbar.MessageQueue = msgqueue

            End Using

        End If

    End Sub

End Class
